/**
 * Run the answer key's checks over a seed file, write what each record said, and (optionally) the
 * SQL that loads it once the migration exists (S46).
 *
 *   npm run answer-key -- check eval/answer-key/seed-2026-10-06.jsonl \
 *     [--out eval/answer-key/run-<date>.jsonl] [--sql out.sql] [--run-id <id>] [--relay relay.json]
 *
 * --relay names a JSON file of { "<url>": { "status": n, "body": "..." } } answers fetched by another
 * path (Supabase pg_net, when this machine's proxy refuses a host). A relayed answer is used exactly
 * as received and every row says which URLs came that way (`relayed`). Everything else is fetched
 * live. Nothing here is a route, and nothing in the stamp path imports it.
 *
 * It needs no Supabase credentials: it reads public records and writes files.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { checkSpec } from '../../src/answer-key/sources';
import type { FetchLike, Finding, SeedClaim } from '../../src/answer-key/types';

type Relay = Record<string, { status: number; body: string }>;

export interface RunRow {
  seed: string;
  claim: string;
  outcome: Finding['outcome'];
  reason: string;
  checker: string;
  record?: Finding['record'];
  /** URLs answered from the relay file rather than fetched from this machine. */
  relayed: string[];
}

export function parseSeed(text: string): SeedClaim[] {
  return text
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l, i) => {
      const row = JSON.parse(l) as SeedClaim;
      if (!row || typeof row.id !== 'string' || typeof row.claim !== 'string' || !row.spec || typeof row.spec !== 'object') {
        throw new Error(`seed line ${i + 1} is not { id, claim, spec }`);
      }
      return row;
    });
}

export async function runSeed(seed: readonly SeedClaim[], live: FetchLike, relay: Relay = {}, env?: Record<string, string | undefined>): Promise<RunRow[]> {
  const rows: RunRow[] = [];
  for (const s of seed) {
    const relayed: string[] = [];
    const fetch: FetchLike = async (url, init) => {
      const hit = relay[url];
      if (hit) {
        relayed.push(url);
        return { status: hit.status, text: async () => hit.body };
      }
      return live(url, init);
    };
    const f = await checkSpec(s.spec, { fetch, ...(env ? { env } : {}) });
    rows.push({ seed: s.id, claim: s.claim, outcome: f.outcome, reason: f.reason, checker: f.checker, ...(f.record ? { record: f.record } : {}), relayed });
  }
  return rows;
}

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const json = (v: unknown) => `${lit(JSON.stringify(v))}::jsonb`;

/**
 * Idempotent SQL: claims and records are inserted once (by seed_id / locator), and each check once per
 * run. A new run's check SUPERSEDES the current check of the same claim and checker from an earlier
 * run, so history is kept and the latest reading is the one that counts.
 */
export function toSql(seed: readonly SeedClaim[], rows: readonly RunRow[], runId: string, checkedAt: string): string {
  const out: string[] = ['-- answer key run ' + runId + ' (generated by scripts/answer-key/run.ts; safe to run twice)', 'begin;'];
  const bySeed = new Map(seed.map((s) => [s.id, s]));
  for (const r of rows) {
    const s = bySeed.get(r.seed)!;
    out.push(
      `insert into public.ak_claims (seed_id, claim, spec, source) values (${lit(s.id)}, ${lit(s.claim)}, ${json(s.spec)}, 'curated') on conflict (seed_id) do nothing;`,
    );
    if (r.record) {
      const rec = r.record;
      out.push(
        `insert into public.ak_records (kind, locator, url, sha256, snapshot, fetched_at) values (${lit(rec.kind)}, ${lit(rec.locator)}, ${lit(rec.url)}, ${lit(rec.sha256)}, ${json(rec.snapshot)}, ${lit(rec.fetchedAt)}) on conflict (locator) do nothing;`,
      );
    }
    const claimId = `(select id from public.ak_claims where seed_id = ${lit(s.id)})`;
    const recordId = r.record ? `(select id from public.ak_records where locator = ${lit(r.record.locator)})` : 'null';
    const prior =
      `(select c.id from public.ak_checks c where c.claim_id = ${claimId} and c.checker = ${lit(r.checker)} and c.run_id <> ${lit(runId)} ` +
      `and not exists (select 1 from public.ak_checks n where n.supersedes = c.id) order by c.checked_at desc limit 1)`;
    out.push(
      `insert into public.ak_checks (claim_id, record_id, checker, outcome, reason, run_id, checked_at, supersedes) ` +
        `select ${claimId}, ${recordId}, ${lit(r.checker)}, ${lit(r.outcome)}, ${lit(r.reason)}, ${lit(runId)}, ${lit(checkedAt)}, ${prior} ` +
        `where not exists (select 1 from public.ak_checks where run_id = ${lit(runId)} and claim_id = ${claimId} and checker = ${lit(r.checker)});`,
    );
  }
  out.push('commit;');
  return out.join('\n') + '\n';
}

function arg(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
}

async function main(argv: string[]) {
  if (argv[0] !== 'check' || !argv[1]) {
    console.error('usage: npm run answer-key -- check <seed.jsonl> [--out run.jsonl] [--sql out.sql] [--run-id id] [--relay relay.json]');
    process.exit(2);
  }
  const seed = parseSeed(readFileSync(argv[1], 'utf8'));
  const relayPath = arg(argv, '--relay');
  const relay: Relay = relayPath ? (JSON.parse(readFileSync(relayPath, 'utf8')) as Relay) : {};
  const live: FetchLike = (url, init) => fetch(url, init as RequestInit);
  const checkedAt = new Date().toISOString();
  const runId = arg(argv, '--run-id') ?? `run-${checkedAt.slice(0, 10)}`;
  const rows = await runSeed(seed, live, relay);
  for (const r of rows) {
    console.log(`${r.outcome.padEnd(12)} ${r.seed.padEnd(32)} ${r.reason}${r.relayed.length ? '  [relayed]' : ''}`);
  }
  const counts = rows.reduce<Record<string, number>>((m, r) => ((m[r.outcome] = (m[r.outcome] ?? 0) + 1), m), {});
  console.log(`\n${rows.length} claims: ${counts.supports ?? 0} supports, ${counts.contradicts ?? 0} contradicts, ${counts.unchecked ?? 0} unchecked`);
  const outPath = arg(argv, '--out');
  if (outPath) writeFileSync(outPath, rows.map((r) => JSON.stringify({ run_id: runId, checked_at: checkedAt, ...r })).join('\n') + '\n');
  const sqlPath = arg(argv, '--sql');
  if (sqlPath) writeFileSync(sqlPath, toSql(seed, rows, runId, checkedAt));
}

if (require.main === module) {
  main(process.argv.slice(2)).catch((e) => {
    console.error(e instanceof Error ? e.message : String(e));
    process.exit(1);
  });
}
