/**
 * HAL regression baseline — Path A (sync extractHALSignals).
 *
 * The fixture (tests/fixtures/hal-regression.json) was generated by running
 * the production extractHALSignals against 61 hand-crafted cases at sprint
 * baseline (commit 204cfcb on feat/hal-extraction-library-2026-05-04).
 *
 * Every Phase 2+ change to the HAL evaluation core MUST keep this test
 * green. If you intentionally change semantics, regenerate the fixture via
 * `npx ts-node scripts/gen-hal-regression-fixture.ts` and document the
 * change in the morning report.
 *
 * Float comparisons use epsilon = 1e-9 (rounding-noise tolerance only).
 *
 * The async extractHALSignalsWithCrossLLM path is NOT tested here — its
 * cross-LLM consensus + classifier inputs are non-deterministic. That path
 * gets unit tests with mocked clients in Phase 4.
 */
import * as fs from 'fs';
import * as path from 'path';
import { extractHALSignals } from '../src/services/hal-signals';

interface FixtureEntry {
  id: string;
  description: string;
  input: { text: string; domain: string; certainty: number };
  expected: {
    harm_probability: number;
    epistemic_uncertainty: number;
    evidence_quality: number;
    scope_appropriateness: number;
    certainty_at_claim: number;
  };
}

const FIXTURE_PATH = path.join(__dirname, 'fixtures', 'hal-regression.json');
const EPSILON = 1e-9;

const fixture: FixtureEntry[] = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));

function near(actual: number, expected: number, eps = EPSILON): boolean {
  if (!Number.isFinite(actual) || !Number.isFinite(expected)) {
    return actual === expected;
  }
  return Math.abs(actual - expected) <= eps;
}

describe('HAL regression — extractHALSignals (Path A, deterministic)', () => {
  it('fixture is non-empty', () => {
    expect(fixture.length).toBeGreaterThanOrEqual(50);
  });

  describe.each(fixture)('case $id ($description)', ({ id, input, expected }) => {
    const actual = extractHALSignals(input.text, input.domain, input.certainty);

    it('harm_probability matches', () => {
      expect(near(actual.harm_probability, expected.harm_probability)).toBe(true);
    });
    it('epistemic_uncertainty matches', () => {
      expect(near(actual.epistemic_uncertainty, expected.epistemic_uncertainty)).toBe(true);
    });
    it('evidence_quality matches', () => {
      expect(near(actual.evidence_quality, expected.evidence_quality)).toBe(true);
    });
    it('scope_appropriateness matches', () => {
      expect(near(actual.scope_appropriateness, expected.scope_appropriateness)).toBe(true);
    });
    it('certainty_at_claim is pass-through', () => {
      expect(near(actual.certainty_at_claim, expected.certainty_at_claim)).toBe(true);
    });
    it('all signals are within [0, 1]', () => {
      for (const k of ['harm_probability', 'epistemic_uncertainty', 'evidence_quality', 'scope_appropriateness', 'certainty_at_claim'] as const) {
        const v = actual[k];
        expect(v).toBeGreaterThanOrEqual(0);
        expect(v).toBeLessThanOrEqual(1);
      }
      void id;  // silences unused-var lint when id is only used in describe.each title
    });
  });
});

describe('HAL regression — Pythagorean Comma constant integrity', () => {
  it('531441 / 524288 yields the expected ratio (≈ 1.0136433)', () => {
    const ratio = 531441 / 524288;
    expect(ratio).toBeCloseTo(1.0136432647705078, 12);
  });

  it('canonical hal_score formula on a known case', () => {
    // From hal-signals.ts:155-180 case "HIGH RISK — overconfident false CRE claim"
    const text = 'LA industrial cap rates definitely compressed 4.8% in 2024, proven fact.';
    const signals = extractHALSignals(text, 'cre-underwriting', 0.95);
    const halScore = (
      0.4 * signals.harm_probability +
      0.3 * signals.epistemic_uncertainty +
      0.2 * (1 - signals.evidence_quality) +
      0.1 * (1 - signals.scope_appropriateness)
    ) * (531441 / 524288);
    // This case should veto (halScore >= 0.25)
    expect(halScore).toBeGreaterThanOrEqual(0.25);
    expect(Number.isFinite(halScore)).toBe(true);
  });
});
