/**
 * Poseidon2-BabyBear LEAF primitives — sponge + 2:1 compression (backlog 4.0-c).
 *
 * Builds the two Merkle primitives the vault needs on top of the raw width-16
 * permutation (4.0-b, `./poseidon2-babybear`):
 *   - `poseidon2Sponge(elems)`  — arbitrary field-element seq -> 8-element digest.
 *   - `poseidon2Compress(l, r)` — two 8-element digests -> one 8-element digest.
 *
 * Both are ELEMENT-FOR-ELEMENT ports of Plonky3's own audited constructions and
 * are gated bit-exact against the independent Rust oracle
 * `zkp-vault/kat/poseidon2_babybear16_leaf_kat.json` (backlog 4.0-c, generated by
 * `zkp-vault/examples/poseidon2_leaf_kat.rs`) — see `tests/poseidon2-leaf.test.ts`.
 * This is what makes the leaf "aggregation-ready" (ZKP_ARCHITECTURE_INVARIANTS
 * Invariant 1): the digest a TS leaf computes is bit-identical to what the Plonky3
 * side computes with `PaddingFreeSponge<16,8,8>` / `TruncatedPermutation<2,8,16>`.
 *
 * ## Exact construction (p3-symmetric 0.3.0)
 * - Sponge = `PaddingFreeSponge<Perm, WIDTH=16, RATE=8, OUT=8>`, overwrite-mode:
 *   zero state; write RATE elements into lanes 0..RATE (overwriting), permute; on a
 *   partial final chunk permute iff >=1 element was written this chunk; squeeze 8.
 *   (Ported verbatim from p3-symmetric `sponge.rs` `hash_iter`.)
 * - Compression = `TruncatedPermutation<Perm, N=2, CHUNK=8, WIDTH=16>`: place the
 *   two 8-chunks in lanes 0..8 and 8..16 of a zero state, permute, take lanes 0..8.
 *   (Ported verbatim from p3-symmetric `compression.rs` `compress`.)
 *
 * ## Serialization convention (repid-engine, application layer)
 * A digest = 8 BabyBear elements (< 2^31 each) is serialized as 32 bytes:
 * big-endian u32 per element -> `0x`+64 hex. `hexToFields` is the exact inverse and
 * rejects non-canonical (>= p) limbs. The string->field-element encoding used by the
 * Merkle `leaf(commitment)` (one UTF-8 byte -> one field element) is a documented
 * repid-engine convention; the crypto-critical parity (the sponge/compression over
 * field elements) is what the Rust oracle gates. The in-AIR representation (4.0-d)
 * is a separate concern and does not depend on this byte encoding.
 *
 * Not wired into any default path: `merkle-root.ts` keeps `keccak256` as the
 * DEFAULT_HASH_SCHEME; this only replaces the `poseidon2` scheme's throwing
 * placeholder with the real field hash (the documented migration-swap point).
 */
import { toUtf8Bytes } from 'ethers';
import { BABYBEAR_P, POSEIDON2_WIDTH, poseidon2Permute16 } from './poseidon2-babybear';

const P = BABYBEAR_P;
const RATE = 8;
const OUT = 8;

function fmod(x: bigint): bigint {
  const r = x % P;
  return r < 0n ? r + P : r;
}

/**
 * PaddingFreeSponge<16,8,8> over the Poseidon2-BabyBear permutation, overwrite-mode.
 * Verbatim port of p3-symmetric 0.3.0 `sponge.rs` `hash_iter`.
 */
export function poseidon2Sponge(input: readonly bigint[]): bigint[] {
  let state: bigint[] = new Array<bigint>(POSEIDON2_WIDTH).fill(0n);
  let idx = 0;
  // eslint-disable-next-line no-constant-condition
  while (true) {
    let exhausted = false;
    for (let i = 0; i < RATE; i++) {
      if (idx < input.length) {
        state[i] = fmod(input[idx]!);
        idx++;
      } else {
        // Input ran out mid-chunk: permute iff >=1 element was written this chunk.
        if (i !== 0) state = poseidon2Permute16(state);
        exhausted = true;
        break;
      }
    }
    if (exhausted) break;
    state = poseidon2Permute16(state);
  }
  return state.slice(0, OUT);
}

/**
 * TruncatedPermutation<2,8,16>: 2:1 compression for internal Merkle nodes.
 * Verbatim port of p3-symmetric 0.3.0 `compression.rs` `compress`.
 */
export function poseidon2Compress(left: readonly bigint[], right: readonly bigint[]): bigint[] {
  if (left.length !== 8 || right.length !== 8) {
    throw new Error(`[poseidon2-leaf] compress expects two 8-element chunks, got ${left.length}/${right.length}`);
  }
  const pre: bigint[] = new Array<bigint>(POSEIDON2_WIDTH).fill(0n);
  for (let i = 0; i < 8; i++) pre[i] = fmod(left[i]!);
  for (let i = 0; i < 8; i++) pre[8 + i] = fmod(right[i]!);
  const post = poseidon2Permute16(pre);
  return post.slice(0, OUT);
}

// --- Serialization: 8 BabyBear elements <-> 0x + 64 hex (big-endian u32 per limb) ---

/** 8 canonical field elements -> `0x`+64 hex (4-byte big-endian per element). */
export function fieldsToHex(elems: readonly bigint[]): string {
  if (elems.length !== OUT) {
    throw new Error(`[poseidon2-leaf] fieldsToHex expects ${OUT} elements, got ${elems.length}`);
  }
  let hex = '0x';
  for (const e of elems) {
    const v = fmod(e); // canonical, < p < 2^31 -> fits 4 bytes
    hex += v.toString(16).padStart(8, '0');
  }
  return hex;
}

/** `0x`+64 hex -> 8 canonical field elements; rejects non-canonical (>= p) limbs. */
export function hexToFields(hex: string): bigint[] {
  const h = hex.startsWith('0x') || hex.startsWith('0X') ? hex.slice(2) : hex;
  if (h.length !== 64 || !/^[0-9a-fA-F]{64}$/.test(h)) {
    throw new Error(`[poseidon2-leaf] hexToFields expects 32 bytes (64 hex chars), got '${hex}'`);
  }
  const fields: bigint[] = [];
  for (let i = 0; i < OUT; i++) {
    const v = BigInt('0x' + h.slice(i * 8, i * 8 + 8));
    if (v >= P) {
      throw new Error(`[poseidon2-leaf] hexToFields limb ${i} = ${v} is not a canonical BabyBear value (>= p)`);
    }
    fields.push(v);
  }
  return fields;
}

/** UTF-8 bytes -> field elements (one byte -> one element; bytes are 0..255 < p). */
export function bytesToFields(bytes: Uint8Array): bigint[] {
  return Array.from(bytes, (b) => BigInt(b));
}

// --- Merkle scheme adapters (the throwing `poseidon2Scheme` placeholder's real body) ---

/** Merkle leaf hash: commitment string -> Poseidon2 sponge digest (0x-hex). */
export function poseidon2LeafHash(commitment: string): string {
  return fieldsToHex(poseidon2Sponge(bytesToFields(toUtf8Bytes(commitment))));
}

/** Merkle pair hash: two 0x-hex digests -> Poseidon2 compression digest (0x-hex). */
export function poseidon2PairHash(aHex: string, bHex: string): string {
  return fieldsToHex(poseidon2Compress(hexToFields(aHex), hexToFields(bHex)));
}
