-- R4 Pen Test Findings (Grok as external model probe; similar for DeepSeek/Qwen)
-- test_run_id = 'r4-2026-06-04-grok-probe'
-- Insert to red_team_results (table from prior sprints; assume columns: test_run_id, attack_type, payload, finding, severity, repro, fix, rollback, created_at)

INSERT INTO red_team_results (test_run_id, attack_type, payload, finding, severity, repro, fix, rollback, created_at) VALUES
('r4-2026-06-04-grok-probe', 'f2-authz-spoof', 'shared REPID_API_KEYS env + agent_id=other', 'F2 fix in route.ts enforces binding (403 for env key + specific agent_id), but other routes (e.g. some x402, legacy) may not have the post-F2 check. Shared env key holders could impersonate if path misses the EVERY auth path enforcement.', 'high', 'Use env key token with agent_id param in /llm or score endpoints not covered by the route.ts llmRouter check; observe if score event written under spoofed agent.', 'Audit all auth paths (routes, services, workers) for the F2 binding assert outside isEnvKey block. Enforce in middleware.', 'revert the F2 commit temporarily', now()),
('r4-2026-06-04-grok-probe', 'x402-replay', 'reuse x_payment_header from prior settle response', 'In x402-inbound and gate, xPaymentHeader used for idempotency, but no explicit timestamp/nonce window or signature validation visible in hot paths; relies on upstream facilitator?', 'high', 'Capture valid xPaymentHeader from successful /x402 response, replay to x402-inbound with same payload within short time; check if duplicate settlement or cost applied twice.', 'Add strict replay protection: unique constraint + created_at window + optional sig on header in x402-gate.ts and inbound route.', 'drop unique for debug', now()),
('r4-2026-06-04-grok-probe', 'controller-ssrf', 'user-controlled url in controller calls (e.g. hitl notify)', 'CONTROLLER_BASE or urls from config/task may allow SSRF if not validated; AbortController timeout but external fetch in notify/hitl may leak or hang on bad host.', 'med', 'In task with bad controller_url or in notify, observe if internal network probed or error details leaked.', 'Whitelist controller hosts, use internal only for controller, sanitize urls.', 'disable abort for test', now()),
('r4-2026-06-04-grok-probe', 'rls-anon-read', 'anon key .from(x402_settlements).select() pre RLS-33 apply', 'Current RLS (from lockdown) may have service_role only or no policy on x402_settlements/agent_services, allowing anon/auth to read sensitive settlement data (owner amounts, agents).', 'high', 'Use anon key (from .env or pooler), query x402_settlements or agent_services; succeeds if no restrictive policy.', 'Apply the clean RLS-33 migration (owner for x402, public for agent_services; leave creds deny). Verify with anon query fails post apply.', 'DROP the owner policy', now());
