ALTER TABLE repid_score_events DROP CONSTRAINT IF EXISTS repid_score_events_event_type_check;
ALTER TABLE repid_score_events ADD CONSTRAINT repid_score_events_event_type_check
CHECK (event_type = ANY (ARRAY[
  'CHALLENGE_WIN', 'CHALLENGE_LOSS', 'CHALLENGE_DRAW', 'EPISTEMIC_VIOLATION',
  'CONSTITUTIONAL_VIOLATION', 'PREDICTION_RESOLVE', 'STAKE', 'GENESIS', 'REFERRAL',
  'PEACEMAKER', 'SELF_MONITOR', 'DECAY', 'MIRROR_TEST_MODE7', 'CONSTITUTIONAL_PASS',
  'CODE_CONTRIBUTION', 'WORKFLOW_CONTRIBUTION', 'TOOL_PIONEER', 'AGENT_TEACHING',
  'AUDIT_CONTRIBUTION', 'CONSTITUTIONAL_AUDIT', 'MCP_TOOL_CALL',
  'LATENCY_OPPORTUNITY_LEARNING', 'BOUNTY_CLAIM', 'BOUNTY_COMPLETE', 'BOUNTY_VERIFY',
  'HAL_SCORE_EVENT', 'PAPER_TRADE_OUTCOME',
  'VALIDATION_PASSED', 'VALIDATION_FAILED', 'VALIDATOR_REWARD', 'VALIDATOR_PENALTY',
  'SERVICE_FULFILLED',
  'SERVICE_SATISFIED'
]));
