/**
 * FAMILY-DISJOINT JURY for a sampled call (§7 HARD RULE — no self-grading).
 * OUTPUT_PATH: src/decisioning/jury-assembly.ts
 * SPEC: PRIORITY_B_ANFIS_DECISIONING_CHARTER_v1.md §7.
 *
 * THE RULE (§7): the quorum that LABELS a call's quality must NOT share the model family of the model
 * that GENERATED the answer — else the jury marks its own homework. This module takes a sampled call
 * (from the verification floor / label queue), reads which model produced it, and assembles a jury whose
 * families exclude that generating family.
 *
 * WIRING, NOT REIMPLEMENTATION (task constraint): the disjoint assembly + rotation + belt-and-suspenders
 * re-check all live in src/decisioning/disjointness.ts (assembleDisjointJudges) and the family truth in
 * family-registry.ts (resolveFamily). This module ONLY:
 *   1) turns the generating (provider, model) into a single-element "candidate" (so assembleDisjointJudges
 *      excludes its family), and
 *   2) calls assembleDisjointJudges(candidate, pool, k, seed).
 * It adds NO new family logic and NO new rotation — a duplicate would risk drifting from the gate.
 *
 * ADVISORY PURITY (R3): pure. No DB writes, no routing. Returns the assembly result; the caller persists
 * it to decisioning_label_queue.jury_models/jury_families (migration FILE). PROMOTION-GATED.
 *
 * HARD-FAIL propagation: if the generating model or any pool model is unmapped, assembleDisjointJudges'
 * resolveFamily throws UnmappedFamilyError (register-first) — we do NOT catch-and-guess (§7 / R4).
 */

import { assembleDisjointJudges, type ModelRef, type JudgeAssembly, checkDisjoint } from './disjointness';
import { resolveFamily } from './family-registry';

/** The generating side of a sampled call (what llm_call_log recorded). */
export interface GeneratingCall {
  /** provider label (reporting only; family is resolved from model). */
  provider?: string;
  /** model string — family-determining field (registry lookup). */
  model: string;
}

export interface JuryForCallResult extends JudgeAssembly {
  /** the family of the generating model (the one excluded from the jury). */
  generatingFamily: string;
  /** convenience: confirmed the assembled jury excludes the generating family (belt-and-suspenders). */
  excludesGeneratingFamily: boolean;
}

/**
 * Assemble a family-disjoint jury of `k` judges for a call generated by `generating`, drawn from `pool`,
 * excluding the generating model's family. Deterministic given `seed` (reuse the call id for auditability).
 *
 * @param generating the model that produced the answer being labeled
 * @param pool       available judge model refs (each registry-mapped)
 * @param k          number of distinct-family judges wanted
 * @param seed       rotation seed (use the call id) — deterministic + auditable
 */
export function assembleJuryForCall(
  generating: GeneratingCall,
  pool: ModelRef[],
  k: number,
  seed: string,
): JuryForCallResult {
  // Resolve the generating family up front (throws UnmappedFamilyError if unmapped — register-first, §7).
  const generatingFamily = resolveFamily(generating.model);

  // Treat the generating model as the sole "candidate" so assembleDisjointJudges excludes its family.
  const candidate: ModelRef[] = [{ provider: generating.provider, model: generating.model }];

  const assembly = assembleDisjointJudges(candidate, pool, k, seed);

  // Belt-and-suspenders: independently confirm the assembled jury does not contain the generating family.
  // (assembleDisjointJudges already re-checks disjointness; this is the §7-specific "no self-grading"
  //  assertion phrased against the generating family explicitly, for the audit record.)
  let excludesGeneratingFamily = true;
  if (assembly.ok) {
    const verify = checkDisjoint(candidate, assembly.judges);
    excludesGeneratingFamily = verify.disjoint && !assembly.judgeFamilies.includes(generatingFamily);
  } else {
    excludesGeneratingFamily = !assembly.judgeFamilies.includes(generatingFamily); // trivially true (empty)
  }

  return { ...assembly, generatingFamily, excludesGeneratingFamily };
}
